[package]
name = "wincent"
version = "0.0.2"
authors = ["Hellager"]
edition = "2021"
repository = "https://github.com/Hellager/wincent-rs"
documentation = "https://docs.rs/wincent/"
readme = "README.md"
license = "MIT"
keywords = ["windows", "recent"]
categories = ["command-line-utilities"]
description = """
A library for handling windows quick access
"""

[dependencies]
env_logger = "0.11.5"
log = "0.4.22"
powershell_script = "1.1.0"
winreg = "0.52.0"
