//! PowerShell script generation strategies used by fallback implementations.

use crate::error::{PowerShellOperation, WincentError};
use crate::WincentResult;

/// Escapes a string for use inside PowerShell single-quoted strings.
///
/// In PowerShell, the only character that needs escaping within `'...'` is the
/// single-quote itself, which is escaped by doubling it (`''`).
fn escape_ps_single_quoted(s: &str) -> String {
    s.replace('\'', "''")
}

/// PowerShell script operation types generated by this crate.
#[allow(dead_code)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub(crate) enum PSScript {
    /// Refresh all Explorer windows.
    RefreshExplorer,
    /// Query both Recent Files and Frequent Folders.
    QueryQuickAccess,
    /// Query Recent Files.
    QueryRecentFile,
    /// Query Frequent Folders.
    QueryFrequentFolder,
    /// Add a file to Recent Files.
    AddRecentFile,
    /// Remove a file from Recent Files.
    RemoveRecentFile,
    /// Pin a folder to Frequent Folders.
    PinToFrequentFolder,
    /// Unpin a folder from Frequent Folders.
    UnpinFromFrequentFolder,
    /// Unpin every folder currently pinned to Frequent Folders.
    EmptyPinnedFolders,
    /// Check whether query operations are available.
    CheckQueryFeasible,
    /// Check whether pin and unpin operations are available.
    CheckPinUnpinFeasible,
}

impl PSScript {
    pub(crate) fn operation(self) -> PowerShellOperation {
        match self {
            PSScript::RefreshExplorer => PowerShellOperation::RefreshExplorer,
            PSScript::QueryQuickAccess => PowerShellOperation::QueryQuickAccess,
            PSScript::QueryRecentFile => PowerShellOperation::QueryRecentFiles,
            PSScript::QueryFrequentFolder => PowerShellOperation::QueryFrequentFolders,
            PSScript::AddRecentFile => PowerShellOperation::AddRecentFile,
            PSScript::RemoveRecentFile => PowerShellOperation::RemoveRecentFile,
            PSScript::PinToFrequentFolder => PowerShellOperation::PinFrequentFolder,
            PSScript::UnpinFromFrequentFolder => PowerShellOperation::UnpinFrequentFolder,
            PSScript::EmptyPinnedFolders => PowerShellOperation::EmptyPinnedFolders,
            PSScript::CheckQueryFeasible => PowerShellOperation::CheckQueryFeasible,
            PSScript::CheckPinUnpinFeasible => PowerShellOperation::CheckPinUnpinFeasible,
        }
    }
}

/// Shell namespace constants
pub(crate) struct ShellNamespaces;

impl ShellNamespaces {
    pub const QUICK_ACCESS: &'static str = "shell:::{679f85cb-0220-4080-b29b-5540cc05aab6}";
    pub const FREQUENT_FOLDERS: &'static str = "shell:::{3936E9E4-D92C-4EEE-A85A-BC16D5EA0819}";
}

/// Script generation strategy interface
pub(crate) trait ScriptStrategy {
    fn generate(&self, parameter: Option<&str>) -> WincentResult<String>;
}

/// Base script strategy providing UTF-8 encoding configuration
pub(crate) struct BaseScriptStrategy;

impl BaseScriptStrategy {
    fn utf8_header() -> &'static str {
        "$OutputEncoding = [Console]::OutputEncoding = [System.Text.Encoding]::UTF8;"
    }

    fn shell_com_object() -> &'static str {
        "$shell = New-Object -ComObject Shell.Application;"
    }
}

/// Strategy for refreshing File Explorer
pub(crate) struct RefreshExplorerStrategy;

impl ScriptStrategy for RefreshExplorerStrategy {
    fn generate(&self, _: Option<&str>) -> WincentResult<String> {
        Ok(format!(
            r#"
    {}
    $shellApplication = New-Object -ComObject Shell.Application;
    $windows = $shellApplication.Windows();
    $windows | ForEach-Object {{ $_.Refresh() }}
"#,
            BaseScriptStrategy::utf8_header()
        ))
    }
}

/// Strategy for querying recent files
pub(crate) struct QueryRecentFileStrategy;

impl ScriptStrategy for QueryRecentFileStrategy {
    fn generate(&self, _: Option<&str>) -> WincentResult<String> {
        Ok(format!(
            r#"
    {}
    {}
    $shell.Namespace('{}').Items() | where {{ $_.IsFolder -eq $false }} | ForEach-Object {{ $_.Path }};
"#,
            BaseScriptStrategy::utf8_header(),
            BaseScriptStrategy::shell_com_object(),
            ShellNamespaces::QUICK_ACCESS
        ))
    }
}

/// Strategy for querying frequent folders
pub(crate) struct QueryFrequentFolderStrategy;

impl ScriptStrategy for QueryFrequentFolderStrategy {
    fn generate(&self, _: Option<&str>) -> WincentResult<String> {
        Ok(format!(
            r#"
    {}
    {}
    $shell.Namespace('{}').Items() | ForEach-Object {{ $_.Path }};
"#,
            BaseScriptStrategy::utf8_header(),
            BaseScriptStrategy::shell_com_object(),
            ShellNamespaces::FREQUENT_FOLDERS
        ))
    }
}

/// Strategy for querying Quick Access
pub(crate) struct QueryQuickAccessStrategy;

impl ScriptStrategy for QueryQuickAccessStrategy {
    fn generate(&self, _: Option<&str>) -> WincentResult<String> {
        Ok(format!(
            r#"
    {}
    {}
    $shell.Namespace('{}').Items() | ForEach-Object {{ $_.Path }};
"#,
            BaseScriptStrategy::utf8_header(),
            BaseScriptStrategy::shell_com_object(),
            ShellNamespaces::QUICK_ACCESS
        ))
    }
}

/// Strategy for adding recent files
/// Placeholder for now, not implemented
pub(crate) struct AddRecentFileStrategy;

impl ScriptStrategy for AddRecentFileStrategy {
    fn generate(&self, parameter: Option<&str>) -> WincentResult<String> {
        let path = escape_ps_single_quoted(parameter.ok_or(WincentError::MissingParameter)?);
        Ok(format!(
            r#"
    {}
    {}
    Write-Output '{}'
"#,
            BaseScriptStrategy::utf8_header(),
            BaseScriptStrategy::shell_com_object(),
            path
        ))
    }
}

/// Strategy for removing recent files
pub(crate) struct RemoveRecentFileStrategy;

impl ScriptStrategy for RemoveRecentFileStrategy {
    fn generate(&self, parameter: Option<&str>) -> WincentResult<String> {
        let path = escape_ps_single_quoted(parameter.ok_or(WincentError::MissingParameter)?);
        Ok(format!(
            r#"
    {}
    {}
    $files = $shell.Namespace('{}').Items() | where {{$_.IsFolder -eq $false}};
    $target = $files | where {{$_.Path -eq '{}'}};
    $target.InvokeVerb('remove');
"#,
            BaseScriptStrategy::utf8_header(),
            BaseScriptStrategy::shell_com_object(),
            ShellNamespaces::QUICK_ACCESS,
            path
        ))
    }
}

/// Strategy for pinning to frequent folders
pub(crate) struct PinToFrequentFolderStrategy;

impl ScriptStrategy for PinToFrequentFolderStrategy {
    fn generate(&self, parameter: Option<&str>) -> WincentResult<String> {
        let path = escape_ps_single_quoted(parameter.ok_or(WincentError::MissingParameter)?);
        Ok(format!(
            r#"
    {}
    {}
    $shell.Namespace('{}').Self.InvokeVerb('pintohome');
"#,
            BaseScriptStrategy::utf8_header(),
            BaseScriptStrategy::shell_com_object(),
            path
        ))
    }
}

/// Strategy for unpinning from frequent folders
pub(crate) struct UnpinFromFrequentFolderStrategy;

impl ScriptStrategy for UnpinFromFrequentFolderStrategy {
    fn generate(&self, parameter: Option<&str>) -> WincentResult<String> {
        let path = escape_ps_single_quoted(parameter.ok_or(WincentError::MissingParameter)?);
        Ok(format!(
            r#"
    {header}
    {shell}

    $isWin11 = (Get-CimInstance -Class Win32_OperatingSystem).Caption -Match "Windows 11"
    if ($isWin11)
    {{
        $shell.Namespace('{path}').Self.InvokeVerb('pintohome')
    }}
    else
    {{
        $folders = $shell.Namespace('{frequent_folders}').Items();
        $target = $folders | Where-Object {{$_.Path -eq '{path}'}};
        $target.InvokeVerb('unpinfromhome');    
    }} 
"#,
            header = BaseScriptStrategy::utf8_header(),
            shell = BaseScriptStrategy::shell_com_object(),
            frequent_folders = ShellNamespaces::FREQUENT_FOLDERS,
            path = path
        ))
    }
}

/// Strategy for emptying pinned folders
pub(crate) struct EmptyPinnedFoldersStrategy;

impl ScriptStrategy for EmptyPinnedFoldersStrategy {
    fn generate(&self, _: Option<&str>) -> WincentResult<String> {
        Ok(format!(
            r#"
    {}
    {}
    $shell.Namespace('{}').Items() | ForEach-Object {{ $_.InvokeVerb('unpinfromhome') }};
"#,
            BaseScriptStrategy::utf8_header(),
            BaseScriptStrategy::shell_com_object(),
            ShellNamespaces::FREQUENT_FOLDERS,
        ))
    }
}

/// Strategy for checking query feasibility
pub(crate) struct CheckQueryFeasibleStrategy;

impl ScriptStrategy for CheckQueryFeasibleStrategy {
    fn generate(&self, _: Option<&str>) -> WincentResult<String> {
        Ok(format!(
            r#"
    {}

    $timeout = 5

    $scriptBlock = {{
        $shell = New-Object -ComObject Shell.Application
        $shell.Namespace('{}').Items() | ForEach-Object {{ $_.Path }};
    }}.ToString()

    $arguments = "-Command & {{$scriptBlock}}"
    $process = Start-Process powershell -ArgumentList $arguments -NoNewWindow -PassThru

    if (-not $process.WaitForExit($timeout * 1000)) {{
        try {{
            $process.Kill()
            Write-Error "Process execution timed out (${{timeout}}s), forcefully terminated"
            exit 1
        }}
        catch {{
            Write-Error "Error occurred while terminating process: $_"
            exit 1
        }}
    }}
"#,
            BaseScriptStrategy::utf8_header(),
            ShellNamespaces::QUICK_ACCESS
        ))
    }
}

/// Strategy for checking pin/unpin feasibility
pub(crate) struct CheckPinUnpinFeasibleStrategy;

impl ScriptStrategy for CheckPinUnpinFeasibleStrategy {
    fn generate(&self, _: Option<&str>) -> WincentResult<String> {
        Ok(format!(
            r#"
    {}

    $currentPath = $PSScriptRoot
    $scriptBlock = {{
        param($scriptPath)
        $shell = New-Object -ComObject Shell.Application
        $shell.Namespace($scriptPath).Self.InvokeVerb('pintohome')

        Start-Sleep -Seconds 3

        $isWin11 = (Get-CimInstance -Class Win32_OperatingSystem).Caption -Match "Windows 11"
        if ($isWin11) 
        {{
            $shell.Namespace($scriptPath).Self.InvokeVerb('pintohome')
        }}
        else
        {{
            $folders = $shell.Namespace('{}').Items();
            $target = $folders | Where-Object {{$_.Path -eq $scriptPath}};
            $target.InvokeVerb('unpinfromhome');
        }}
    }}.ToString()

    $arguments = "-Command & {{$scriptBlock}} -scriptPath '$currentPath'"
    $process = Start-Process powershell -ArgumentList $arguments -NoNewWindow -PassThru

    $timeout = 10
    if (-not $process.WaitForExit($timeout * 1000)) {{
        try {{
            $process.Kill()
            Write-Error "Process execution timed out (${{timeout}}s), forcefully terminated"
            exit 1
        }}
        catch {{
            Write-Error "Error occurred while terminating process: $_"
            exit 1
        }}
    }}
"#,
            BaseScriptStrategy::utf8_header(),
            ShellNamespaces::FREQUENT_FOLDERS
        ))
    }
}

/// Strategy factory for retrieving script generation strategies
pub(crate) struct ScriptStrategyFactory;

impl ScriptStrategyFactory {
    /// Retrieves the strategy instance for the specified script type
    pub fn get_strategy(script_type: PSScript) -> WincentResult<Box<dyn ScriptStrategy>> {
        Ok(match script_type {
            PSScript::RefreshExplorer => Box::new(RefreshExplorerStrategy),
            PSScript::QueryQuickAccess => Box::new(QueryQuickAccessStrategy),
            PSScript::QueryRecentFile => Box::new(QueryRecentFileStrategy),
            PSScript::QueryFrequentFolder => Box::new(QueryFrequentFolderStrategy),
            PSScript::AddRecentFile => Box::new(AddRecentFileStrategy),
            PSScript::RemoveRecentFile => Box::new(RemoveRecentFileStrategy),
            PSScript::PinToFrequentFolder => Box::new(PinToFrequentFolderStrategy),
            PSScript::UnpinFromFrequentFolder => Box::new(UnpinFromFrequentFolderStrategy),
            PSScript::CheckQueryFeasible => Box::new(CheckQueryFeasibleStrategy),
            PSScript::CheckPinUnpinFeasible => Box::new(CheckPinUnpinFeasibleStrategy),
            PSScript::EmptyPinnedFolders => Box::new(EmptyPinnedFoldersStrategy),
        })
    }

    /// Generates script content
    pub fn generate_script(
        script_type: PSScript,
        parameter: Option<&str>,
    ) -> WincentResult<String> {
        let strategy = Self::get_strategy(script_type)?;
        strategy.generate(parameter)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_pin_frequent_folder_script_generation() {
        let path = "C:\\Users\\User\\Documents";
        let script =
            ScriptStrategyFactory::generate_script(PSScript::PinToFrequentFolder, Some(path))
                .unwrap();
        assert!(script.contains("pintohome"));
        assert!(script.contains(path));
        assert!(script.contains(BaseScriptStrategy::shell_com_object()));
    }

    #[test]
    fn test_unpin_frequent_folder_script_generation() {
        let path = "C:\\Users\\User\\Documents";
        let script =
            ScriptStrategyFactory::generate_script(PSScript::UnpinFromFrequentFolder, Some(path))
                .unwrap();
        assert!(script.contains("unpinfromhome"));
        // Win11 branch must also be present
        assert!(script.contains("pintohome"));
        assert!(script.contains(ShellNamespaces::FREQUENT_FOLDERS));
        assert!(script.contains(&format!(
            "$shell.Namespace('{}').Self.InvokeVerb('pintohome')",
            path
        )));
        assert!(
            !script.contains("{path}"),
            "Win11 unpin branch must not contain an unsubstituted path placeholder"
        );
    }

    #[test]
    fn test_remove_recent_files_script_generation() {
        let path = "C:\\Users\\User\\Documents";
        let script =
            ScriptStrategyFactory::generate_script(PSScript::RemoveRecentFile, Some(path)).unwrap();
        assert!(script.contains("remove"));
        assert!(script.contains(ShellNamespaces::QUICK_ACCESS));
        assert!(script.contains(path));
    }

    #[test]
    fn test_query_feasibility_check_script() {
        let script =
            ScriptStrategyFactory::generate_script(PSScript::CheckQueryFeasible, None).unwrap();
        assert!(script.contains(ShellNamespaces::QUICK_ACCESS));
        assert!(script.contains("WaitForExit"));
        assert!(script.contains("timeout"));
    }

    #[test]
    fn test_pin_unpin_feasibility_check_script() {
        let script =
            ScriptStrategyFactory::generate_script(PSScript::CheckPinUnpinFeasible, None).unwrap();
        assert!(script.contains("pintohome"));
        assert!(script.contains("unpinfromhome"));
        assert!(script.contains(ShellNamespaces::FREQUENT_FOLDERS));
        assert!(script.contains("WaitForExit"));
    }

    #[test]
    fn test_script_content_validity() {
        let path = "C:\\Users\\User\\Documents";

        // RefreshExplorer: must call Refresh() on open windows
        let refresh =
            ScriptStrategyFactory::generate_script(PSScript::RefreshExplorer, None).unwrap();
        assert!(refresh.contains("Refresh()"));
        assert!(refresh.contains("Windows()"));

        // QueryQuickAccess: must enumerate Quick Access namespace
        let qqa = ScriptStrategyFactory::generate_script(PSScript::QueryQuickAccess, None).unwrap();
        assert!(qqa.contains(ShellNamespaces::QUICK_ACCESS));
        assert!(qqa.contains("$_.Path"));

        // QueryRecentFile: must filter IsFolder == false
        let qrf = ScriptStrategyFactory::generate_script(PSScript::QueryRecentFile, None).unwrap();
        assert!(qrf.contains("IsFolder -eq $false"));
        assert!(qrf.contains(ShellNamespaces::QUICK_ACCESS));

        // QueryFrequentFolder: must enumerate FrequentFolders namespace
        let qff =
            ScriptStrategyFactory::generate_script(PSScript::QueryFrequentFolder, None).unwrap();
        assert!(qff.contains(ShellNamespaces::FREQUENT_FOLDERS));
        assert!(qff.contains("$_.Path"));

        // AddRecentFile: must Write-Output the path
        let arf =
            ScriptStrategyFactory::generate_script(PSScript::AddRecentFile, Some(path)).unwrap();
        assert!(arf.contains("Write-Output"));
        assert!(arf.contains(path));

        // RemoveRecentFile: must invoke 'remove' verb
        let rrf =
            ScriptStrategyFactory::generate_script(PSScript::RemoveRecentFile, Some(path)).unwrap();
        assert!(rrf.contains("'remove'"));
        assert!(rrf.contains(ShellNamespaces::QUICK_ACCESS));

        // PinToFrequentFolder: must invoke 'pintohome' on path namespace self
        let pin = ScriptStrategyFactory::generate_script(PSScript::PinToFrequentFolder, Some(path))
            .unwrap();
        assert!(pin.contains("pintohome"));

        // UnpinFromFrequentFolder: must have both Win10 and Win11 branches
        let unpin =
            ScriptStrategyFactory::generate_script(PSScript::UnpinFromFrequentFolder, Some(path))
                .unwrap();
        assert!(unpin.contains("unpinfromhome"));
        assert!(unpin.contains("pintohome"));

        // EmptyPinnedFolders: must invoke 'unpinfromhome' on every item in FrequentFolders
        let epf =
            ScriptStrategyFactory::generate_script(PSScript::EmptyPinnedFolders, None).unwrap();
        assert!(epf.contains("unpinfromhome"));
        assert!(epf.contains(ShellNamespaces::FREQUENT_FOLDERS));
        assert!(epf.contains("ForEach-Object"));

        // Feasibility scripts must reference timeout and subprocess management
        let cqf =
            ScriptStrategyFactory::generate_script(PSScript::CheckQueryFeasible, None).unwrap();
        assert!(cqf.contains("WaitForExit"));

        let cpf =
            ScriptStrategyFactory::generate_script(PSScript::CheckPinUnpinFeasible, None).unwrap();
        assert!(cpf.contains("WaitForExit"));
    }

    #[test]
    fn test_missing_parameter_error() {
        // Scripts that require a path parameter must return MissingParameter when called
        // with None, not panic or produce empty output.
        let requires_param = [
            PSScript::AddRecentFile,
            PSScript::RemoveRecentFile,
            PSScript::PinToFrequentFolder,
            PSScript::UnpinFromFrequentFolder,
        ];
        for script_type in &requires_param {
            let result = ScriptStrategyFactory::generate_script(*script_type, None);
            assert!(
                matches!(result, Err(crate::error::WincentError::MissingParameter)),
                "{:?} with None parameter should return MissingParameter, got {:?}",
                script_type,
                result
            );
        }
    }

    /// Verifies that `ScriptStrategyFactory::get_strategy` successfully returns a
    /// strategy for every `PSScript` variant, and that `generate_script` on each
    /// no-parameter variant produces non-empty output.  This replaces the previous
    /// mock-panic test which exercised no real factory behaviour.
    #[test]
    fn test_factory_covers_all_variants() {
        let no_param_variants = [
            PSScript::RefreshExplorer,
            PSScript::QueryQuickAccess,
            PSScript::QueryRecentFile,
            PSScript::QueryFrequentFolder,
            PSScript::EmptyPinnedFolders,
            PSScript::CheckQueryFeasible,
            PSScript::CheckPinUnpinFeasible,
        ];
        for variant in &no_param_variants {
            let strategy = ScriptStrategyFactory::get_strategy(*variant)
                .unwrap_or_else(|e| panic!("{:?}: get_strategy failed: {:?}", variant, e));
            let script = strategy
                .generate(None)
                .unwrap_or_else(|e| panic!("{:?}: generate(None) failed: {:?}", variant, e));
            assert!(
                !script.is_empty(),
                "{:?}: generated script is empty",
                variant
            );
        }

        let path = "C:\\Users\\User\\Documents";
        let param_variants = [
            PSScript::AddRecentFile,
            PSScript::RemoveRecentFile,
            PSScript::PinToFrequentFolder,
            PSScript::UnpinFromFrequentFolder,
        ];
        for variant in &param_variants {
            let strategy = ScriptStrategyFactory::get_strategy(*variant)
                .unwrap_or_else(|e| panic!("{:?}: get_strategy failed: {:?}", variant, e));
            let script = strategy
                .generate(Some(path))
                .unwrap_or_else(|e| panic!("{:?}: generate(Some(path)) failed: {:?}", variant, e));
            assert!(
                !script.is_empty(),
                "{:?}: generated script is empty",
                variant
            );
        }
    }

    #[test]
    fn test_apostrophe_path_escaping() {
        let path = "C:\\Users\\O'Brien\\Documents";
        let escaped_path = "C:\\Users\\O''Brien\\Documents";
        let cases = [
            (
                PSScript::AddRecentFile,
                format!("Write-Output '{}'", escaped_path),
            ),
            (
                PSScript::RemoveRecentFile,
                format!("$_.Path -eq '{}'", escaped_path),
            ),
            (
                PSScript::PinToFrequentFolder,
                format!(
                    "$shell.Namespace('{}').Self.InvokeVerb('pintohome')",
                    escaped_path
                ),
            ),
            (
                PSScript::UnpinFromFrequentFolder,
                format!("$_.Path -eq '{}'", escaped_path),
            ),
        ];
        for (script_type, expected_fragment) in &cases {
            let script = ScriptStrategyFactory::generate_script(*script_type, Some(path))
                .unwrap_or_else(|_| panic!("{:?} generation failed", script_type));
            assert!(
                script.contains(expected_fragment.as_str()),
                "{:?}: expected fragment not found in script.\nExpected: {}\nScript: {}",
                script_type,
                expected_fragment,
                script
            );
            assert!(
                !script.contains("O'Brien"),
                "{:?}: raw unescaped apostrophe found in script",
                script_type
            );
        }

        // UnpinFromFrequentFolder also contains a Win11 branch that calls pintohome with
        // the escaped path. Verify that branch is correctly escaped too.
        let unpin_script =
            ScriptStrategyFactory::generate_script(PSScript::UnpinFromFrequentFolder, Some(path))
                .expect("UnpinFromFrequentFolder generation failed");
        let win11_fragment = format!(
            "$shell.Namespace('{}').Self.InvokeVerb('pintohome')",
            escaped_path
        );
        assert!(
            unpin_script.contains(&win11_fragment),
            "UnpinFromFrequentFolder Win11 branch: expected fragment not found.\nExpected: {}\nScript: {}",
            win11_fragment, unpin_script
        );
        assert!(
            !unpin_script.contains("{path}"),
            "UnpinFromFrequentFolder Win11 branch must not leave a literal {{path}} placeholder"
        );
    }
}
