name: Build and Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    name: Publish
    runs-on: windows-latest
    steps:
      - name: Print GitHub Ref
        run: 'echo "Current GitHub ref is: ${{ github.ref }}"'

      - uses: actions/checkout@v4
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      
      - name: Update version in Cargo.toml
        shell: bash
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          
          sed -i "s/^version = \".*\"/version = \"$VERSION\"/" Cargo.toml
          
          echo "Updated version to: $VERSION"
          grep "^version = " Cargo.toml
      
      - name: Exit
        run: |
          exit -1
