name: Build and Publish

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        if: ${{ github.event_name != 'workflow_dispatch' }}
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Build the crate
        if: ${{ github.event_name != 'workflow_dispatch' }}
        run: cargo build --release

      - name: Publish to crates.io
        if: ${{ github.event_name != 'workflow_dispatch' }}
        shell: bash
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: cargo publish --token "$CARGO_REGISTRY_TOKEN"

      - name: Create Archive
        uses: thedoctor0/zip-release@0.7.5
        with:
          type: 'zip'
          filename: 'wincent-rs.zip'
          exclusions: '*.git*'

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "draft"
          files: |
            wincent-rs.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub token for authentication
